SELECT * INTO OUTFILE '/tmp/all.csv'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
FROM all_observations;

SELECT * INTO OUTFILE '/tmp/hourly.csv'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
FROM hourly_observations;

SELECT * INTO OUTFILE '/tmpdaily.csv'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
FROM daily_observations;